import type { Metadata, Viewport } from "next";
import { Bricolage_Grotesque, Inter } from "next/font/google";
import { META_DESCRIPTION, PAGE_TITLE, SITE_URL, TOOL_NAME } from "@/lib/brand";
import "./globals.css";

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ["600", "700"],
  variable: "--font-bricolage",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  // metadataBase makes OG/social/canonical URLs absolute.
  metadataBase: new URL(SITE_URL),
  title: PAGE_TITLE,
  description: META_DESCRIPTION,
  applicationName: TOOL_NAME,
  // Sub-pages override this with their own path (trailingSlash form).
  alternates: { canonical: "/" },
  keywords: [
    "spin the wheel",
    "wheel spinner",
    "spinner wheel",
    "random picker",
    "decision maker",
    "random name picker",
  ],
  openGraph: {
    title: PAGE_TITLE,
    description: META_DESCRIPTION,
    url: "/",
    siteName: TOOL_NAME,
    locale: "en_US",
    type: "website",
  },
  twitter: {
    // No twitter-image file — Twitter/X falls back to the og:image
    // generated by app/opengraph-image.tsx.
    card: "summary_large_image",
    title: PAGE_TITLE,
    description: META_DESCRIPTION,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export const viewport: Viewport = {
  themeColor: "#FAFAF9",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${bricolage.variable} ${inter.variable} font-sans bg-bg text-text antialiased min-h-dvh`}
      >
        {children}
      </body>
    </html>
  );
}
